#pragma once
#define EXPORT_VAR extern
#define EXPORT_FUNC
// Standard C++ includes
#include <random>
#include <string>
#include <stdexcept>

// Standard C includes
#include <cassert>
#include <cstdint>
#define DT 1.00000000000000006e-01
typedef double scalar;
#define SCALAR_MIN 2.22507385850720138e-308
#define SCALAR_MAX 1.79769313486231571e+308

#define TIME_MIN 2.22507385850720138e-308
#define TIME_MAX 1.79769313486231571e+308

// ------------------------------------------------------------------------
// bit tool macros
#define B(x,i) ((x) & (0x80000000 >> (i))) //!< Extract the bit at the specified position i from x
#define setB(x,i) x= ((x) | (0x80000000 >> (i))) //!< Set the bit at the specified position i in x to 1
#define delB(x,i) x= ((x) & (~(0x80000000 >> (i)))) //!< Set the bit at the specified position i in x to 0

extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------
EXPORT_VAR unsigned long long iT;
EXPORT_VAR double t;

// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double initTime;
EXPORT_VAR double initSparseTime;
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
// ------------------------------------------------------------------------
// local neuron groups
// ------------------------------------------------------------------------
#define spikeCount_ln glbSpkCntln[0]
#define spike_ln glbSpkln
#define glbSpkShiftln 0

EXPORT_VAR unsigned int* glbSpkCntln;
EXPORT_VAR unsigned int* d_glbSpkCntln;
EXPORT_VAR unsigned int* glbSpkln;
EXPORT_VAR unsigned int* d_glbSpkln;
EXPORT_VAR scalar* Vln;
EXPORT_VAR scalar* d_Vln;
EXPORT_VAR scalar* aln;
EXPORT_VAR scalar* d_aln;
#define spikeCount_or glbSpkCntor[0]
#define spike_or glbSpkor
#define glbSpkShiftor 0

EXPORT_VAR unsigned int* glbSpkCntor;
EXPORT_VAR unsigned int* d_glbSpkCntor;
EXPORT_VAR unsigned int* glbSpkor;
EXPORT_VAR unsigned int* d_glbSpkor;
EXPORT_VAR scalar* r0or;
EXPORT_VAR scalar* d_r0or;
EXPORT_VAR scalar* rb_0or;
EXPORT_VAR scalar* d_rb_0or;
EXPORT_VAR scalar* ra_0or;
EXPORT_VAR scalar* d_ra_0or;
EXPORT_VAR scalar* rb_1or;
EXPORT_VAR scalar* d_rb_1or;
EXPORT_VAR scalar* ra_1or;
EXPORT_VAR scalar* d_ra_1or;
EXPORT_VAR scalar* rb_2or;
EXPORT_VAR scalar* d_rb_2or;
EXPORT_VAR scalar* ra_2or;
EXPORT_VAR scalar* d_ra_2or;
EXPORT_VAR scalar* raor;
EXPORT_VAR scalar* d_raor;
EXPORT_VAR scalar* kp1cn_0or;
EXPORT_VAR scalar* d_kp1cn_0or;
EXPORT_VAR scalar* km1_0or;
EXPORT_VAR scalar* d_km1_0or;
EXPORT_VAR scalar* kp2_0or;
EXPORT_VAR scalar* d_kp2_0or;
EXPORT_VAR scalar* km2_0or;
EXPORT_VAR scalar* d_km2_0or;
EXPORT_VAR scalar* kp1cn_1or;
EXPORT_VAR scalar* d_kp1cn_1or;
EXPORT_VAR scalar* km1_1or;
EXPORT_VAR scalar* d_km1_1or;
EXPORT_VAR scalar* kp2_1or;
EXPORT_VAR scalar* d_kp2_1or;
EXPORT_VAR scalar* km2_1or;
EXPORT_VAR scalar* d_km2_1or;
EXPORT_VAR scalar* kp1cn_2or;
EXPORT_VAR scalar* d_kp1cn_2or;
EXPORT_VAR scalar* km1_2or;
EXPORT_VAR scalar* d_km1_2or;
EXPORT_VAR scalar* kp2_2or;
EXPORT_VAR scalar* d_kp2_2or;
EXPORT_VAR scalar* km2_2or;
EXPORT_VAR scalar* d_km2_2or;
EXPORT_VAR scalar* kp1cn_0_0or;
EXPORT_VAR scalar* d_kp1cn_0_0or;
EXPORT_VAR scalar* kp2_0_0or;
EXPORT_VAR scalar* d_kp2_0_0or;
EXPORT_VAR scalar* kp1cn_0_1or;
EXPORT_VAR scalar* d_kp1cn_0_1or;
EXPORT_VAR scalar* kp2_0_1or;
EXPORT_VAR scalar* d_kp2_0_1or;
EXPORT_VAR scalar* kp1cn_0_2or;
EXPORT_VAR scalar* d_kp1cn_0_2or;
EXPORT_VAR scalar* kp2_0_2or;
EXPORT_VAR scalar* d_kp2_0_2or;
EXPORT_VAR scalar* kp1cn_0_3or;
EXPORT_VAR scalar* d_kp1cn_0_3or;
EXPORT_VAR scalar* kp2_0_3or;
EXPORT_VAR scalar* d_kp2_0_3or;
EXPORT_VAR scalar* kp1cn_0_4or;
EXPORT_VAR scalar* d_kp1cn_0_4or;
EXPORT_VAR scalar* kp2_0_4or;
EXPORT_VAR scalar* d_kp2_0_4or;
EXPORT_VAR scalar* kp1cn_0_5or;
EXPORT_VAR scalar* d_kp1cn_0_5or;
EXPORT_VAR scalar* kp2_0_5or;
EXPORT_VAR scalar* d_kp2_0_5or;
EXPORT_VAR scalar* kp1cn_0_6or;
EXPORT_VAR scalar* d_kp1cn_0_6or;
EXPORT_VAR scalar* kp2_0_6or;
EXPORT_VAR scalar* d_kp2_0_6or;
EXPORT_VAR scalar* kp1cn_0_7or;
EXPORT_VAR scalar* d_kp1cn_0_7or;
EXPORT_VAR scalar* kp2_0_7or;
EXPORT_VAR scalar* d_kp2_0_7or;
EXPORT_VAR scalar* kp1cn_0_8or;
EXPORT_VAR scalar* d_kp1cn_0_8or;
EXPORT_VAR scalar* kp2_0_8or;
EXPORT_VAR scalar* d_kp2_0_8or;
EXPORT_VAR scalar* kp1cn_0_9or;
EXPORT_VAR scalar* d_kp1cn_0_9or;
EXPORT_VAR scalar* kp2_0_9or;
EXPORT_VAR scalar* d_kp2_0_9or;
EXPORT_VAR scalar* kp1cn_0_10or;
EXPORT_VAR scalar* d_kp1cn_0_10or;
EXPORT_VAR scalar* kp2_0_10or;
EXPORT_VAR scalar* d_kp2_0_10or;
EXPORT_VAR scalar* kp1cn_0_11or;
EXPORT_VAR scalar* d_kp1cn_0_11or;
EXPORT_VAR scalar* kp2_0_11or;
EXPORT_VAR scalar* d_kp2_0_11or;
EXPORT_VAR scalar* kp1cn_0_12or;
EXPORT_VAR scalar* d_kp1cn_0_12or;
EXPORT_VAR scalar* kp2_0_12or;
EXPORT_VAR scalar* d_kp2_0_12or;
EXPORT_VAR scalar* kp1cn_0_13or;
EXPORT_VAR scalar* d_kp1cn_0_13or;
EXPORT_VAR scalar* kp2_0_13or;
EXPORT_VAR scalar* d_kp2_0_13or;
EXPORT_VAR scalar* kp1cn_0_14or;
EXPORT_VAR scalar* d_kp1cn_0_14or;
EXPORT_VAR scalar* kp2_0_14or;
EXPORT_VAR scalar* d_kp2_0_14or;
EXPORT_VAR scalar* kp1cn_0_15or;
EXPORT_VAR scalar* d_kp1cn_0_15or;
EXPORT_VAR scalar* kp2_0_15or;
EXPORT_VAR scalar* d_kp2_0_15or;
EXPORT_VAR scalar* kp1cn_0_16or;
EXPORT_VAR scalar* d_kp1cn_0_16or;
EXPORT_VAR scalar* kp2_0_16or;
EXPORT_VAR scalar* d_kp2_0_16or;
EXPORT_VAR scalar* kp1cn_0_17or;
EXPORT_VAR scalar* d_kp1cn_0_17or;
EXPORT_VAR scalar* kp2_0_17or;
EXPORT_VAR scalar* d_kp2_0_17or;
EXPORT_VAR scalar* kp1cn_0_18or;
EXPORT_VAR scalar* d_kp1cn_0_18or;
EXPORT_VAR scalar* kp2_0_18or;
EXPORT_VAR scalar* d_kp2_0_18or;
EXPORT_VAR scalar* kp1cn_0_19or;
EXPORT_VAR scalar* d_kp1cn_0_19or;
EXPORT_VAR scalar* kp2_0_19or;
EXPORT_VAR scalar* d_kp2_0_19or;
EXPORT_VAR scalar* kp1cn_0_20or;
EXPORT_VAR scalar* d_kp1cn_0_20or;
EXPORT_VAR scalar* kp2_0_20or;
EXPORT_VAR scalar* d_kp2_0_20or;
EXPORT_VAR scalar* kp1cn_0_21or;
EXPORT_VAR scalar* d_kp1cn_0_21or;
EXPORT_VAR scalar* kp2_0_21or;
EXPORT_VAR scalar* d_kp2_0_21or;
EXPORT_VAR scalar* kp1cn_0_22or;
EXPORT_VAR scalar* d_kp1cn_0_22or;
EXPORT_VAR scalar* kp2_0_22or;
EXPORT_VAR scalar* d_kp2_0_22or;
EXPORT_VAR scalar* kp1cn_0_23or;
EXPORT_VAR scalar* d_kp1cn_0_23or;
EXPORT_VAR scalar* kp2_0_23or;
EXPORT_VAR scalar* d_kp2_0_23or;
EXPORT_VAR scalar* kp1cn_0_24or;
EXPORT_VAR scalar* d_kp1cn_0_24or;
EXPORT_VAR scalar* kp2_0_24or;
EXPORT_VAR scalar* d_kp2_0_24or;
EXPORT_VAR scalar* kp1cn_0_25or;
EXPORT_VAR scalar* d_kp1cn_0_25or;
EXPORT_VAR scalar* kp2_0_25or;
EXPORT_VAR scalar* d_kp2_0_25or;
EXPORT_VAR scalar* kp1cn_0_26or;
EXPORT_VAR scalar* d_kp1cn_0_26or;
EXPORT_VAR scalar* kp2_0_26or;
EXPORT_VAR scalar* d_kp2_0_26or;
EXPORT_VAR scalar* kp1cn_0_27or;
EXPORT_VAR scalar* d_kp1cn_0_27or;
EXPORT_VAR scalar* kp2_0_27or;
EXPORT_VAR scalar* d_kp2_0_27or;
EXPORT_VAR scalar* kp1cn_0_28or;
EXPORT_VAR scalar* d_kp1cn_0_28or;
EXPORT_VAR scalar* kp2_0_28or;
EXPORT_VAR scalar* d_kp2_0_28or;
EXPORT_VAR scalar* kp1cn_0_29or;
EXPORT_VAR scalar* d_kp1cn_0_29or;
EXPORT_VAR scalar* kp2_0_29or;
EXPORT_VAR scalar* d_kp2_0_29or;
EXPORT_VAR scalar* kp1cn_0_30or;
EXPORT_VAR scalar* d_kp1cn_0_30or;
EXPORT_VAR scalar* kp2_0_30or;
EXPORT_VAR scalar* d_kp2_0_30or;
EXPORT_VAR scalar* kp1cn_0_31or;
EXPORT_VAR scalar* d_kp1cn_0_31or;
EXPORT_VAR scalar* kp2_0_31or;
EXPORT_VAR scalar* d_kp2_0_31or;
EXPORT_VAR scalar* kp1cn_0_32or;
EXPORT_VAR scalar* d_kp1cn_0_32or;
EXPORT_VAR scalar* kp2_0_32or;
EXPORT_VAR scalar* d_kp2_0_32or;
EXPORT_VAR scalar* kp1cn_0_33or;
EXPORT_VAR scalar* d_kp1cn_0_33or;
EXPORT_VAR scalar* kp2_0_33or;
EXPORT_VAR scalar* d_kp2_0_33or;
EXPORT_VAR scalar* kp1cn_0_34or;
EXPORT_VAR scalar* d_kp1cn_0_34or;
EXPORT_VAR scalar* kp2_0_34or;
EXPORT_VAR scalar* d_kp2_0_34or;
EXPORT_VAR scalar* kp1cn_0_35or;
EXPORT_VAR scalar* d_kp1cn_0_35or;
EXPORT_VAR scalar* kp2_0_35or;
EXPORT_VAR scalar* d_kp2_0_35or;
EXPORT_VAR scalar* kp1cn_0_36or;
EXPORT_VAR scalar* d_kp1cn_0_36or;
EXPORT_VAR scalar* kp2_0_36or;
EXPORT_VAR scalar* d_kp2_0_36or;
EXPORT_VAR scalar* kp1cn_0_37or;
EXPORT_VAR scalar* d_kp1cn_0_37or;
EXPORT_VAR scalar* kp2_0_37or;
EXPORT_VAR scalar* d_kp2_0_37or;
EXPORT_VAR scalar* kp1cn_0_38or;
EXPORT_VAR scalar* d_kp1cn_0_38or;
EXPORT_VAR scalar* kp2_0_38or;
EXPORT_VAR scalar* d_kp2_0_38or;
EXPORT_VAR scalar* kp1cn_0_39or;
EXPORT_VAR scalar* d_kp1cn_0_39or;
EXPORT_VAR scalar* kp2_0_39or;
EXPORT_VAR scalar* d_kp2_0_39or;
EXPORT_VAR scalar* kp1cn_0_40or;
EXPORT_VAR scalar* d_kp1cn_0_40or;
EXPORT_VAR scalar* kp2_0_40or;
EXPORT_VAR scalar* d_kp2_0_40or;
EXPORT_VAR scalar* kp1cn_0_41or;
EXPORT_VAR scalar* d_kp1cn_0_41or;
EXPORT_VAR scalar* kp2_0_41or;
EXPORT_VAR scalar* d_kp2_0_41or;
EXPORT_VAR scalar* kp1cn_0_42or;
EXPORT_VAR scalar* d_kp1cn_0_42or;
EXPORT_VAR scalar* kp2_0_42or;
EXPORT_VAR scalar* d_kp2_0_42or;
EXPORT_VAR scalar* kp1cn_0_43or;
EXPORT_VAR scalar* d_kp1cn_0_43or;
EXPORT_VAR scalar* kp2_0_43or;
EXPORT_VAR scalar* d_kp2_0_43or;
EXPORT_VAR scalar* kp1cn_0_44or;
EXPORT_VAR scalar* d_kp1cn_0_44or;
EXPORT_VAR scalar* kp2_0_44or;
EXPORT_VAR scalar* d_kp2_0_44or;
EXPORT_VAR scalar* kp1cn_0_45or;
EXPORT_VAR scalar* d_kp1cn_0_45or;
EXPORT_VAR scalar* kp2_0_45or;
EXPORT_VAR scalar* d_kp2_0_45or;
EXPORT_VAR scalar* kp1cn_0_46or;
EXPORT_VAR scalar* d_kp1cn_0_46or;
EXPORT_VAR scalar* kp2_0_46or;
EXPORT_VAR scalar* d_kp2_0_46or;
EXPORT_VAR scalar* kp1cn_0_47or;
EXPORT_VAR scalar* d_kp1cn_0_47or;
EXPORT_VAR scalar* kp2_0_47or;
EXPORT_VAR scalar* d_kp2_0_47or;
EXPORT_VAR scalar* kp1cn_0_48or;
EXPORT_VAR scalar* d_kp1cn_0_48or;
EXPORT_VAR scalar* kp2_0_48or;
EXPORT_VAR scalar* d_kp2_0_48or;
EXPORT_VAR scalar* kp1cn_0_49or;
EXPORT_VAR scalar* d_kp1cn_0_49or;
EXPORT_VAR scalar* kp2_0_49or;
EXPORT_VAR scalar* d_kp2_0_49or;
EXPORT_VAR scalar* kp1cn_0_50or;
EXPORT_VAR scalar* d_kp1cn_0_50or;
EXPORT_VAR scalar* kp2_0_50or;
EXPORT_VAR scalar* d_kp2_0_50or;
EXPORT_VAR scalar* kp1cn_0_51or;
EXPORT_VAR scalar* d_kp1cn_0_51or;
EXPORT_VAR scalar* kp2_0_51or;
EXPORT_VAR scalar* d_kp2_0_51or;
EXPORT_VAR scalar* kp1cn_0_52or;
EXPORT_VAR scalar* d_kp1cn_0_52or;
EXPORT_VAR scalar* kp2_0_52or;
EXPORT_VAR scalar* d_kp2_0_52or;
EXPORT_VAR scalar* kp1cn_0_53or;
EXPORT_VAR scalar* d_kp1cn_0_53or;
EXPORT_VAR scalar* kp2_0_53or;
EXPORT_VAR scalar* d_kp2_0_53or;
EXPORT_VAR scalar* kp1cn_0_54or;
EXPORT_VAR scalar* d_kp1cn_0_54or;
EXPORT_VAR scalar* kp2_0_54or;
EXPORT_VAR scalar* d_kp2_0_54or;
EXPORT_VAR scalar* kp1cn_0_55or;
EXPORT_VAR scalar* d_kp1cn_0_55or;
EXPORT_VAR scalar* kp2_0_55or;
EXPORT_VAR scalar* d_kp2_0_55or;
EXPORT_VAR scalar* kp1cn_0_56or;
EXPORT_VAR scalar* d_kp1cn_0_56or;
EXPORT_VAR scalar* kp2_0_56or;
EXPORT_VAR scalar* d_kp2_0_56or;
EXPORT_VAR scalar* kp1cn_0_57or;
EXPORT_VAR scalar* d_kp1cn_0_57or;
EXPORT_VAR scalar* kp2_0_57or;
EXPORT_VAR scalar* d_kp2_0_57or;
EXPORT_VAR scalar* kp1cn_0_58or;
EXPORT_VAR scalar* d_kp1cn_0_58or;
EXPORT_VAR scalar* kp2_0_58or;
EXPORT_VAR scalar* d_kp2_0_58or;
EXPORT_VAR scalar* kp1cn_0_59or;
EXPORT_VAR scalar* d_kp1cn_0_59or;
EXPORT_VAR scalar* kp2_0_59or;
EXPORT_VAR scalar* d_kp2_0_59or;
EXPORT_VAR scalar* kp1cn_0_60or;
EXPORT_VAR scalar* d_kp1cn_0_60or;
EXPORT_VAR scalar* kp2_0_60or;
EXPORT_VAR scalar* d_kp2_0_60or;
EXPORT_VAR scalar* kp1cn_0_61or;
EXPORT_VAR scalar* d_kp1cn_0_61or;
EXPORT_VAR scalar* kp2_0_61or;
EXPORT_VAR scalar* d_kp2_0_61or;
EXPORT_VAR scalar* kp1cn_0_62or;
EXPORT_VAR scalar* d_kp1cn_0_62or;
EXPORT_VAR scalar* kp2_0_62or;
EXPORT_VAR scalar* d_kp2_0_62or;
EXPORT_VAR scalar* kp1cn_0_63or;
EXPORT_VAR scalar* d_kp1cn_0_63or;
EXPORT_VAR scalar* kp2_0_63or;
EXPORT_VAR scalar* d_kp2_0_63or;
EXPORT_VAR scalar* kp1cn_0_64or;
EXPORT_VAR scalar* d_kp1cn_0_64or;
EXPORT_VAR scalar* kp2_0_64or;
EXPORT_VAR scalar* d_kp2_0_64or;
EXPORT_VAR scalar* kp1cn_0_65or;
EXPORT_VAR scalar* d_kp1cn_0_65or;
EXPORT_VAR scalar* kp2_0_65or;
EXPORT_VAR scalar* d_kp2_0_65or;
EXPORT_VAR scalar* kp1cn_0_66or;
EXPORT_VAR scalar* d_kp1cn_0_66or;
EXPORT_VAR scalar* kp2_0_66or;
EXPORT_VAR scalar* d_kp2_0_66or;
EXPORT_VAR scalar* kp1cn_0_67or;
EXPORT_VAR scalar* d_kp1cn_0_67or;
EXPORT_VAR scalar* kp2_0_67or;
EXPORT_VAR scalar* d_kp2_0_67or;
EXPORT_VAR scalar* kp1cn_0_68or;
EXPORT_VAR scalar* d_kp1cn_0_68or;
EXPORT_VAR scalar* kp2_0_68or;
EXPORT_VAR scalar* d_kp2_0_68or;
EXPORT_VAR scalar* kp1cn_0_69or;
EXPORT_VAR scalar* d_kp1cn_0_69or;
EXPORT_VAR scalar* kp2_0_69or;
EXPORT_VAR scalar* d_kp2_0_69or;
EXPORT_VAR scalar* kp1cn_0_70or;
EXPORT_VAR scalar* d_kp1cn_0_70or;
EXPORT_VAR scalar* kp2_0_70or;
EXPORT_VAR scalar* d_kp2_0_70or;
EXPORT_VAR scalar* kp1cn_0_71or;
EXPORT_VAR scalar* d_kp1cn_0_71or;
EXPORT_VAR scalar* kp2_0_71or;
EXPORT_VAR scalar* d_kp2_0_71or;
EXPORT_VAR scalar* kp1cn_0_72or;
EXPORT_VAR scalar* d_kp1cn_0_72or;
EXPORT_VAR scalar* kp2_0_72or;
EXPORT_VAR scalar* d_kp2_0_72or;
EXPORT_VAR scalar* kp1cn_0_73or;
EXPORT_VAR scalar* d_kp1cn_0_73or;
EXPORT_VAR scalar* kp2_0_73or;
EXPORT_VAR scalar* d_kp2_0_73or;
EXPORT_VAR scalar* kp1cn_0_74or;
EXPORT_VAR scalar* d_kp1cn_0_74or;
EXPORT_VAR scalar* kp2_0_74or;
EXPORT_VAR scalar* d_kp2_0_74or;
EXPORT_VAR scalar* kp1cn_0_75or;
EXPORT_VAR scalar* d_kp1cn_0_75or;
EXPORT_VAR scalar* kp2_0_75or;
EXPORT_VAR scalar* d_kp2_0_75or;
EXPORT_VAR scalar* kp1cn_0_76or;
EXPORT_VAR scalar* d_kp1cn_0_76or;
EXPORT_VAR scalar* kp2_0_76or;
EXPORT_VAR scalar* d_kp2_0_76or;
EXPORT_VAR scalar* kp1cn_0_77or;
EXPORT_VAR scalar* d_kp1cn_0_77or;
EXPORT_VAR scalar* kp2_0_77or;
EXPORT_VAR scalar* d_kp2_0_77or;
EXPORT_VAR scalar* kp1cn_0_78or;
EXPORT_VAR scalar* d_kp1cn_0_78or;
EXPORT_VAR scalar* kp2_0_78or;
EXPORT_VAR scalar* d_kp2_0_78or;
EXPORT_VAR scalar* kp1cn_0_79or;
EXPORT_VAR scalar* d_kp1cn_0_79or;
EXPORT_VAR scalar* kp2_0_79or;
EXPORT_VAR scalar* d_kp2_0_79or;
EXPORT_VAR scalar* kp1cn_0_80or;
EXPORT_VAR scalar* d_kp1cn_0_80or;
EXPORT_VAR scalar* kp2_0_80or;
EXPORT_VAR scalar* d_kp2_0_80or;
EXPORT_VAR scalar* kp1cn_0_81or;
EXPORT_VAR scalar* d_kp1cn_0_81or;
EXPORT_VAR scalar* kp2_0_81or;
EXPORT_VAR scalar* d_kp2_0_81or;
EXPORT_VAR scalar* kp1cn_0_82or;
EXPORT_VAR scalar* d_kp1cn_0_82or;
EXPORT_VAR scalar* kp2_0_82or;
EXPORT_VAR scalar* d_kp2_0_82or;
EXPORT_VAR scalar* kp1cn_0_83or;
EXPORT_VAR scalar* d_kp1cn_0_83or;
EXPORT_VAR scalar* kp2_0_83or;
EXPORT_VAR scalar* d_kp2_0_83or;
EXPORT_VAR scalar* kp1cn_0_84or;
EXPORT_VAR scalar* d_kp1cn_0_84or;
EXPORT_VAR scalar* kp2_0_84or;
EXPORT_VAR scalar* d_kp2_0_84or;
EXPORT_VAR scalar* kp1cn_0_85or;
EXPORT_VAR scalar* d_kp1cn_0_85or;
EXPORT_VAR scalar* kp2_0_85or;
EXPORT_VAR scalar* d_kp2_0_85or;
EXPORT_VAR scalar* kp1cn_0_86or;
EXPORT_VAR scalar* d_kp1cn_0_86or;
EXPORT_VAR scalar* kp2_0_86or;
EXPORT_VAR scalar* d_kp2_0_86or;
EXPORT_VAR scalar* kp1cn_0_87or;
EXPORT_VAR scalar* d_kp1cn_0_87or;
EXPORT_VAR scalar* kp2_0_87or;
EXPORT_VAR scalar* d_kp2_0_87or;
EXPORT_VAR scalar* kp1cn_0_88or;
EXPORT_VAR scalar* d_kp1cn_0_88or;
EXPORT_VAR scalar* kp2_0_88or;
EXPORT_VAR scalar* d_kp2_0_88or;
EXPORT_VAR scalar* kp1cn_0_89or;
EXPORT_VAR scalar* d_kp1cn_0_89or;
EXPORT_VAR scalar* kp2_0_89or;
EXPORT_VAR scalar* d_kp2_0_89or;
EXPORT_VAR scalar* kp1cn_0_90or;
EXPORT_VAR scalar* d_kp1cn_0_90or;
EXPORT_VAR scalar* kp2_0_90or;
EXPORT_VAR scalar* d_kp2_0_90or;
EXPORT_VAR scalar* kp1cn_0_91or;
EXPORT_VAR scalar* d_kp1cn_0_91or;
EXPORT_VAR scalar* kp2_0_91or;
EXPORT_VAR scalar* d_kp2_0_91or;
EXPORT_VAR scalar* kp1cn_0_92or;
EXPORT_VAR scalar* d_kp1cn_0_92or;
EXPORT_VAR scalar* kp2_0_92or;
EXPORT_VAR scalar* d_kp2_0_92or;
EXPORT_VAR scalar* kp1cn_0_93or;
EXPORT_VAR scalar* d_kp1cn_0_93or;
EXPORT_VAR scalar* kp2_0_93or;
EXPORT_VAR scalar* d_kp2_0_93or;
EXPORT_VAR scalar* kp1cn_0_94or;
EXPORT_VAR scalar* d_kp1cn_0_94or;
EXPORT_VAR scalar* kp2_0_94or;
EXPORT_VAR scalar* d_kp2_0_94or;
EXPORT_VAR scalar* kp1cn_0_95or;
EXPORT_VAR scalar* d_kp1cn_0_95or;
EXPORT_VAR scalar* kp2_0_95or;
EXPORT_VAR scalar* d_kp2_0_95or;
EXPORT_VAR scalar* kp1cn_0_96or;
EXPORT_VAR scalar* d_kp1cn_0_96or;
EXPORT_VAR scalar* kp2_0_96or;
EXPORT_VAR scalar* d_kp2_0_96or;
EXPORT_VAR scalar* kp1cn_0_97or;
EXPORT_VAR scalar* d_kp1cn_0_97or;
EXPORT_VAR scalar* kp2_0_97or;
EXPORT_VAR scalar* d_kp2_0_97or;
EXPORT_VAR scalar* kp1cn_0_98or;
EXPORT_VAR scalar* d_kp1cn_0_98or;
EXPORT_VAR scalar* kp2_0_98or;
EXPORT_VAR scalar* d_kp2_0_98or;
EXPORT_VAR scalar* kp1cn_0_99or;
EXPORT_VAR scalar* d_kp1cn_0_99or;
EXPORT_VAR scalar* kp2_0_99or;
EXPORT_VAR scalar* d_kp2_0_99or;
#define spikeCount_orn glbSpkCntorn[0]
#define spike_orn glbSpkorn
#define glbSpkShiftorn 0

EXPORT_VAR unsigned int* glbSpkCntorn;
EXPORT_VAR unsigned int* d_glbSpkCntorn;
EXPORT_VAR unsigned int* glbSpkorn;
EXPORT_VAR unsigned int* d_glbSpkorn;
EXPORT_VAR scalar* Vorn;
EXPORT_VAR scalar* d_Vorn;
EXPORT_VAR scalar* aorn;
EXPORT_VAR scalar* d_aorn;
#define spikeCount_pn glbSpkCntpn[0]
#define spike_pn glbSpkpn
#define glbSpkShiftpn 0

EXPORT_VAR unsigned int* glbSpkCntpn;
EXPORT_VAR unsigned int* d_glbSpkCntpn;
EXPORT_VAR unsigned int* glbSpkpn;
EXPORT_VAR unsigned int* d_glbSpkpn;
EXPORT_VAR scalar* Vpn;
EXPORT_VAR scalar* d_Vpn;
EXPORT_VAR scalar* apn;
EXPORT_VAR scalar* d_apn;

// ------------------------------------------------------------------------
// custom update variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// pre and postsynaptic variables
// ------------------------------------------------------------------------
EXPORT_VAR double* inSynpn_ln;
EXPORT_VAR double* d_inSynpn_ln;
EXPORT_VAR double* inSynln_ln;
EXPORT_VAR double* d_inSynln_ln;
EXPORT_VAR double* inSynor_ln;
EXPORT_VAR double* d_inSynor_ln;
EXPORT_VAR double* inSynor_orn;
EXPORT_VAR double* d_inSynor_orn;
EXPORT_VAR double* inSynln_pn;
EXPORT_VAR double* d_inSynln_pn;
EXPORT_VAR double* inSynor_pn;
EXPORT_VAR double* d_inSynor_pn;

// ------------------------------------------------------------------------
// synapse connectivity
// ------------------------------------------------------------------------
EXPORT_VAR const unsigned int maxRowLengthor_ln;
EXPORT_VAR unsigned int* rowLengthor_ln;
EXPORT_VAR unsigned int* d_rowLengthor_ln;
EXPORT_VAR uint32_t* indor_ln;
EXPORT_VAR uint32_t* d_indor_ln;
EXPORT_VAR const unsigned int maxRowLengthor_orn;
EXPORT_VAR unsigned int* rowLengthor_orn;
EXPORT_VAR unsigned int* d_rowLengthor_orn;
EXPORT_VAR uint32_t* indor_orn;
EXPORT_VAR uint32_t* d_indor_orn;
EXPORT_VAR const unsigned int maxRowLengthor_pn;
EXPORT_VAR unsigned int* rowLengthor_pn;
EXPORT_VAR unsigned int* d_rowLengthor_pn;
EXPORT_VAR uint32_t* indor_pn;
EXPORT_VAR uint32_t* d_indor_pn;
EXPORT_VAR const unsigned int maxRowLengthpn_ln;
EXPORT_VAR unsigned int* rowLengthpn_ln;
EXPORT_VAR unsigned int* d_rowLengthpn_ln;
EXPORT_VAR uint32_t* indpn_ln;
EXPORT_VAR uint32_t* d_indpn_ln;

// ------------------------------------------------------------------------
// synapse variables
// ------------------------------------------------------------------------
EXPORT_VAR scalar* gln_ln;
EXPORT_VAR scalar* d_gln_ln;
EXPORT_VAR scalar* gln_pn;
EXPORT_VAR scalar* d_gln_pn;
EXPORT_VAR scalar* gpn_ln;
EXPORT_VAR scalar* d_gpn_ln;

EXPORT_FUNC void pushlnSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulllnSpikesFromDevice();
EXPORT_FUNC void pushlnCurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulllnCurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getlnCurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getlnCurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushVlnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullVlnFromDevice();
EXPORT_FUNC void pushCurrentVlnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentVlnFromDevice();
EXPORT_FUNC scalar* getCurrentVln(unsigned int batch = 0); 
EXPORT_FUNC void pushalnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullalnFromDevice();
EXPORT_FUNC void pushCurrentalnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentalnFromDevice();
EXPORT_FUNC scalar* getCurrentaln(unsigned int batch = 0); 
EXPORT_FUNC void pushlnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulllnStateFromDevice();
EXPORT_FUNC void pushorSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullorSpikesFromDevice();
EXPORT_FUNC void pushorCurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullorCurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getorCurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getorCurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushr0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullr0orFromDevice();
EXPORT_FUNC void pushCurrentr0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentr0orFromDevice();
EXPORT_FUNC scalar* getCurrentr0or(unsigned int batch = 0); 
EXPORT_FUNC void pushrb_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrb_0orFromDevice();
EXPORT_FUNC void pushCurrentrb_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrb_0orFromDevice();
EXPORT_FUNC scalar* getCurrentrb_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushra_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullra_0orFromDevice();
EXPORT_FUNC void pushCurrentra_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentra_0orFromDevice();
EXPORT_FUNC scalar* getCurrentra_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushrb_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrb_1orFromDevice();
EXPORT_FUNC void pushCurrentrb_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrb_1orFromDevice();
EXPORT_FUNC scalar* getCurrentrb_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushra_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullra_1orFromDevice();
EXPORT_FUNC void pushCurrentra_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentra_1orFromDevice();
EXPORT_FUNC scalar* getCurrentra_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushrb_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrb_2orFromDevice();
EXPORT_FUNC void pushCurrentrb_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrb_2orFromDevice();
EXPORT_FUNC scalar* getCurrentrb_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushra_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullra_2orFromDevice();
EXPORT_FUNC void pushCurrentra_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentra_2orFromDevice();
EXPORT_FUNC scalar* getCurrentra_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushraorToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullraorFromDevice();
EXPORT_FUNC void pushCurrentraorToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentraorFromDevice();
EXPORT_FUNC scalar* getCurrentraor(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushkm1_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkm1_0orFromDevice();
EXPORT_FUNC void pushCurrentkm1_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkm1_0orFromDevice();
EXPORT_FUNC scalar* getCurrentkm1_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushkm2_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkm2_0orFromDevice();
EXPORT_FUNC void pushCurrentkm2_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkm2_0orFromDevice();
EXPORT_FUNC scalar* getCurrentkm2_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_1orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_1orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushkm1_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkm1_1orFromDevice();
EXPORT_FUNC void pushCurrentkm1_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkm1_1orFromDevice();
EXPORT_FUNC scalar* getCurrentkm1_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_1orFromDevice();
EXPORT_FUNC void pushCurrentkp2_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_1orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushkm2_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkm2_1orFromDevice();
EXPORT_FUNC void pushCurrentkm2_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkm2_1orFromDevice();
EXPORT_FUNC scalar* getCurrentkm2_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_2orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_2orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushkm1_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkm1_2orFromDevice();
EXPORT_FUNC void pushCurrentkm1_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkm1_2orFromDevice();
EXPORT_FUNC scalar* getCurrentkm1_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_2orFromDevice();
EXPORT_FUNC void pushCurrentkp2_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_2orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushkm2_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkm2_2orFromDevice();
EXPORT_FUNC void pushCurrentkm2_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkm2_2orFromDevice();
EXPORT_FUNC scalar* getCurrentkm2_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_0orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_0orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_0orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_0orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_0orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_0or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_1orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_1orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_1orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_1orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_1orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_1or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_2orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_2orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_2orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_2orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_2orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_2or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_3orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_3orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_3orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_3orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_3or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_3orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_3orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_3orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_3orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_3or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_4orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_4orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_4orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_4orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_4or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_4orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_4orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_4orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_4orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_4or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_5orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_5orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_5orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_5orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_5or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_5orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_5orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_5orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_5orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_5or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_6orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_6orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_6orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_6orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_6or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_6orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_6orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_6orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_6orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_6or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_7orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_7orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_7orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_7orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_7or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_7orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_7orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_7orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_7orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_7or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_8orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_8orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_8orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_8orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_8or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_8orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_8orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_8orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_8orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_8or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_9orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_9orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_9orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_9orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_9or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_9orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_9orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_9orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_9orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_9or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_10orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_10orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_10orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_10orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_10or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_10orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_10orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_10orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_10orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_10or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_11orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_11orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_11orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_11orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_11or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_11orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_11orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_11orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_11orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_11or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_12orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_12orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_12orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_12orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_12or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_12orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_12orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_12orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_12orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_12or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_13orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_13orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_13orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_13orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_13or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_13orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_13orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_13orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_13orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_13or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_14orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_14orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_14orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_14orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_14or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_14orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_14orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_14orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_14orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_14or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_15orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_15orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_15orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_15orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_15or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_15orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_15orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_15orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_15orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_15or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_16orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_16orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_16orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_16orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_16or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_16orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_16orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_16orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_16orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_16or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_17orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_17orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_17orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_17orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_17or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_17orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_17orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_17orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_17orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_17or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_18orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_18orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_18orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_18orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_18or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_18orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_18orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_18orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_18orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_18or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_19orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_19orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_19orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_19orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_19or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_19orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_19orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_19orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_19orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_19or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_20orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_20orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_20orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_20orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_20or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_20orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_20orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_20orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_20orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_20or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_21orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_21orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_21orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_21orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_21or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_21orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_21orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_21orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_21orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_21or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_22orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_22orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_22orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_22orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_22or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_22orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_22orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_22orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_22orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_22or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_23orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_23orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_23orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_23orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_23or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_23orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_23orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_23orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_23orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_23or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_24orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_24orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_24orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_24orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_24or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_24orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_24orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_24orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_24orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_24or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_25orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_25orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_25orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_25orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_25or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_25orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_25orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_25orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_25orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_25or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_26orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_26orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_26orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_26orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_26or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_26orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_26orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_26orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_26orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_26or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_27orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_27orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_27orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_27orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_27or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_27orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_27orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_27orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_27orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_27or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_28orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_28orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_28orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_28orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_28or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_28orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_28orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_28orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_28orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_28or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_29orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_29orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_29orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_29orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_29or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_29orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_29orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_29orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_29orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_29or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_30orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_30orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_30orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_30orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_30or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_30orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_30orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_30orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_30orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_30or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_31orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_31orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_31orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_31orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_31or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_31orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_31orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_31orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_31orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_31or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_32orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_32orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_32orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_32orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_32or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_32orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_32orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_32orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_32orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_32or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_33orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_33orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_33orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_33orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_33or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_33orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_33orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_33orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_33orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_33or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_34orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_34orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_34orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_34orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_34or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_34orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_34orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_34orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_34orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_34or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_35orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_35orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_35orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_35orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_35or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_35orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_35orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_35orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_35orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_35or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_36orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_36orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_36orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_36orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_36or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_36orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_36orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_36orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_36orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_36or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_37orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_37orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_37orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_37orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_37or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_37orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_37orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_37orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_37orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_37or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_38orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_38orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_38orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_38orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_38or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_38orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_38orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_38orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_38orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_38or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_39orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_39orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_39orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_39orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_39or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_39orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_39orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_39orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_39orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_39or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_40orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_40orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_40orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_40orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_40or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_40orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_40orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_40orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_40orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_40or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_41orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_41orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_41orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_41orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_41or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_41orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_41orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_41orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_41orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_41or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_42orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_42orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_42orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_42orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_42or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_42orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_42orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_42orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_42orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_42or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_43orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_43orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_43orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_43orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_43or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_43orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_43orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_43orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_43orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_43or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_44orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_44orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_44orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_44orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_44or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_44orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_44orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_44orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_44orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_44or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_45orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_45orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_45orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_45orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_45or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_45orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_45orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_45orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_45orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_45or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_46orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_46orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_46orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_46orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_46or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_46orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_46orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_46orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_46orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_46or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_47orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_47orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_47orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_47orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_47or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_47orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_47orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_47orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_47orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_47or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_48orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_48orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_48orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_48orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_48or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_48orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_48orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_48orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_48orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_48or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_49orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_49orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_49orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_49orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_49or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_49orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_49orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_49orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_49orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_49or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_50orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_50orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_50orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_50orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_50or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_50orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_50orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_50orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_50orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_50or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_51orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_51orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_51orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_51orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_51or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_51orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_51orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_51orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_51orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_51or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_52orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_52orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_52orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_52orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_52or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_52orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_52orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_52orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_52orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_52or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_53orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_53orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_53orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_53orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_53or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_53orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_53orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_53orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_53orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_53or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_54orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_54orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_54orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_54orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_54or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_54orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_54orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_54orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_54orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_54or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_55orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_55orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_55orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_55orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_55or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_55orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_55orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_55orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_55orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_55or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_56orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_56orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_56orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_56orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_56or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_56orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_56orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_56orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_56orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_56or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_57orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_57orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_57orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_57orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_57or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_57orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_57orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_57orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_57orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_57or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_58orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_58orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_58orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_58orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_58or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_58orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_58orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_58orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_58orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_58or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_59orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_59orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_59orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_59orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_59or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_59orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_59orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_59orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_59orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_59or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_60orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_60orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_60orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_60orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_60or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_60orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_60orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_60orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_60orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_60or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_61orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_61orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_61orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_61orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_61or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_61orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_61orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_61orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_61orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_61or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_62orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_62orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_62orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_62orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_62or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_62orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_62orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_62orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_62orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_62or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_63orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_63orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_63orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_63orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_63or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_63orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_63orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_63orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_63orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_63or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_64orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_64orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_64orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_64orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_64or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_64orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_64orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_64orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_64orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_64or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_65orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_65orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_65orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_65orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_65or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_65orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_65orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_65orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_65orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_65or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_66orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_66orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_66orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_66orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_66or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_66orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_66orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_66orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_66orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_66or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_67orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_67orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_67orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_67orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_67or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_67orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_67orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_67orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_67orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_67or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_68orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_68orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_68orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_68orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_68or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_68orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_68orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_68orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_68orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_68or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_69orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_69orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_69orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_69orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_69or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_69orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_69orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_69orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_69orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_69or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_70orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_70orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_70orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_70orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_70or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_70orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_70orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_70orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_70orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_70or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_71orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_71orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_71orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_71orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_71or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_71orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_71orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_71orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_71orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_71or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_72orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_72orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_72orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_72orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_72or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_72orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_72orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_72orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_72orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_72or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_73orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_73orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_73orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_73orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_73or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_73orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_73orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_73orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_73orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_73or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_74orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_74orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_74orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_74orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_74or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_74orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_74orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_74orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_74orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_74or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_75orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_75orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_75orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_75orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_75or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_75orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_75orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_75orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_75orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_75or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_76orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_76orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_76orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_76orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_76or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_76orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_76orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_76orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_76orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_76or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_77orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_77orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_77orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_77orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_77or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_77orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_77orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_77orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_77orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_77or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_78orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_78orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_78orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_78orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_78or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_78orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_78orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_78orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_78orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_78or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_79orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_79orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_79orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_79orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_79or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_79orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_79orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_79orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_79orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_79or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_80orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_80orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_80orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_80orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_80or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_80orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_80orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_80orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_80orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_80or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_81orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_81orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_81orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_81orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_81or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_81orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_81orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_81orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_81orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_81or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_82orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_82orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_82orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_82orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_82or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_82orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_82orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_82orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_82orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_82or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_83orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_83orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_83orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_83orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_83or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_83orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_83orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_83orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_83orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_83or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_84orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_84orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_84orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_84orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_84or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_84orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_84orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_84orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_84orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_84or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_85orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_85orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_85orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_85orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_85or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_85orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_85orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_85orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_85orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_85or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_86orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_86orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_86orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_86orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_86or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_86orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_86orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_86orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_86orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_86or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_87orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_87orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_87orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_87orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_87or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_87orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_87orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_87orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_87orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_87or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_88orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_88orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_88orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_88orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_88or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_88orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_88orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_88orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_88orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_88or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_89orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_89orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_89orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_89orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_89or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_89orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_89orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_89orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_89orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_89or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_90orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_90orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_90orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_90orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_90or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_90orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_90orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_90orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_90orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_90or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_91orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_91orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_91orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_91orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_91or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_91orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_91orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_91orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_91orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_91or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_92orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_92orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_92orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_92orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_92or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_92orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_92orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_92orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_92orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_92or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_93orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_93orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_93orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_93orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_93or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_93orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_93orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_93orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_93orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_93or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_94orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_94orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_94orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_94orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_94or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_94orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_94orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_94orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_94orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_94or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_95orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_95orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_95orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_95orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_95or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_95orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_95orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_95orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_95orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_95or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_96orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_96orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_96orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_96orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_96or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_96orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_96orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_96orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_96orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_96or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_97orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_97orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_97orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_97orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_97or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_97orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_97orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_97orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_97orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_97or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_98orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_98orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_98orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_98orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_98or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_98orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_98orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_98orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_98orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_98or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp1cn_0_99orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp1cn_0_99orFromDevice();
EXPORT_FUNC void pushCurrentkp1cn_0_99orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp1cn_0_99orFromDevice();
EXPORT_FUNC scalar* getCurrentkp1cn_0_99or(unsigned int batch = 0); 
EXPORT_FUNC void pushkp2_0_99orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullkp2_0_99orFromDevice();
EXPORT_FUNC void pushCurrentkp2_0_99orToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentkp2_0_99orFromDevice();
EXPORT_FUNC scalar* getCurrentkp2_0_99or(unsigned int batch = 0); 
EXPORT_FUNC void pushorStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullorStateFromDevice();
EXPORT_FUNC void pushornSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullornSpikesFromDevice();
EXPORT_FUNC void pushornCurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullornCurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getornCurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getornCurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushVornToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullVornFromDevice();
EXPORT_FUNC void pushCurrentVornToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentVornFromDevice();
EXPORT_FUNC scalar* getCurrentVorn(unsigned int batch = 0); 
EXPORT_FUNC void pushaornToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaornFromDevice();
EXPORT_FUNC void pushCurrentaornToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaornFromDevice();
EXPORT_FUNC scalar* getCurrentaorn(unsigned int batch = 0); 
EXPORT_FUNC void pushornStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullornStateFromDevice();
EXPORT_FUNC void pushpnSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullpnSpikesFromDevice();
EXPORT_FUNC void pushpnCurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullpnCurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getpnCurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getpnCurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushVpnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullVpnFromDevice();
EXPORT_FUNC void pushCurrentVpnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentVpnFromDevice();
EXPORT_FUNC scalar* getCurrentVpn(unsigned int batch = 0); 
EXPORT_FUNC void pushapnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullapnFromDevice();
EXPORT_FUNC void pushCurrentapnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentapnFromDevice();
EXPORT_FUNC scalar* getCurrentapn(unsigned int batch = 0); 
EXPORT_FUNC void pushpnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullpnStateFromDevice();
EXPORT_FUNC void pushor_lnConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullor_lnConnectivityFromDevice();
EXPORT_FUNC void pushor_ornConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullor_ornConnectivityFromDevice();
EXPORT_FUNC void pushor_pnConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullor_pnConnectivityFromDevice();
EXPORT_FUNC void pushpn_lnConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullpn_lnConnectivityFromDevice();
EXPORT_FUNC void pushgln_lnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullgln_lnFromDevice();
EXPORT_FUNC void pushinSynln_lnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynln_lnFromDevice();
EXPORT_FUNC void pushln_lnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullln_lnStateFromDevice();
EXPORT_FUNC void pushgln_pnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullgln_pnFromDevice();
EXPORT_FUNC void pushinSynln_pnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynln_pnFromDevice();
EXPORT_FUNC void pushln_pnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullln_pnStateFromDevice();
EXPORT_FUNC void pushinSynor_lnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynor_lnFromDevice();
EXPORT_FUNC void pushor_lnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullor_lnStateFromDevice();
EXPORT_FUNC void pushinSynor_ornToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynor_ornFromDevice();
EXPORT_FUNC void pushor_ornStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullor_ornStateFromDevice();
EXPORT_FUNC void pushinSynor_pnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynor_pnFromDevice();
EXPORT_FUNC void pushor_pnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullor_pnStateFromDevice();
EXPORT_FUNC void pushgpn_lnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullgpn_lnFromDevice();
EXPORT_FUNC void pushinSynpn_lnToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynpn_lnFromDevice();
EXPORT_FUNC void pushpn_lnStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullpn_lnStateFromDevice();
// Runner functions
EXPORT_FUNC void copyStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyStateFromDevice();
EXPORT_FUNC void copyCurrentSpikesFromDevice();
EXPORT_FUNC void copyCurrentSpikeEventsFromDevice();
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC size_t getFreeDeviceMemBytes();
EXPORT_FUNC void stepTime();

// Functions generated by backend
EXPORT_FUNC void updateNeurons(double t); 
EXPORT_FUNC void updateSynapses(double t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
}  // extern "C"
